<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <label>Adjustment No:</label> {{ strtoupper($master->adj_no) }} <br>
        <label>Date:</label> {{ \App\Helpers\CommonHelper::changeDateFormat($master->adj_date) }} <br>
        <label>Warehouse:</label> {{ $master->warehouse_name }} <br>
        <label>Remarks:</label> {{ $master->description }} <br>
        <label>Generated By:</label> {{ $master->username }} <br><br>
    </div>
    
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="table-responsive">
            <table class="table table-bordered sf-table-list">
                <thead>
                    <tr class="bg-primary">
                        <th class="text-center">S.No</th>
                        <th class="text-center">Item Code</th>
                        <th class="text-center">Item Name</th>
                        <th class="text-center">System Qty</th>
                        <th class="text-center">Actual Qty</th>
                        <th class="text-center">Diff Qty</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $counter = 1; ?>
                    @foreach($details as $row)
                        <tr class="text-center">
                            <td>{{ $counter++ }}</td>
                            <td>{{ $row->sku_code }}</td>
                            <td>{{ $row->product_name }}</td>
                            <td>{{ $row->old_qty }}</td>
                            <td>{{ $row->actual_qty }}</td>
                            <td>
                                @if($row->diff_qty > 0)
                                    <span class="label label-success">+{{ $row->diff_qty }}</span>
                                @elseif($row->diff_qty < 0)
                                    <span class="label label-danger">{{ $row->diff_qty }}</span>
                                @else
                                    {{ $row->diff_qty }}
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
